graph TD
    A[Project/Repo] --> |git init / clone| B[Untracked/Modified Files]
    B -->|git add| C[Staged Files]
    C -->|git commit| D[Committed Files]
    C -.->|git restore| I[Unstaged Changes] -.-> B
    D -->|git push| E[Remote Repository]
    D -->|git reset| G[Revert Changes] --> C

    %% Optional actions
    B -.->|git stash| F[Stashed Changes]
    F -.->|git stash pop / apply| B

    D -.->|git merge / pull| H[Merge Changes]--> J
    
    A ==>|git checkout -b| J[New Branch]
    A ==>|git checkout -b| K[Remote Branch]

    style A stroke:#333,stroke-width:4px
    style B stroke:#333,stroke-width:4px
    style C stroke:#333,stroke-width:4px
    style D stroke:#333,stroke-width:4px
    style E stroke:#333,stroke-width:4px
    style F stroke:#333,stroke-width:4px
